export type Category =
  'Chicken' | 'Beef' | 'Seafood' | 'Goat' | 'Pork' | 'Turkey' | 'BBQ' | 'Sausages' | 'Spices';

export type Preparation = 'Whole' | 'Cubed' | 'Boneless' | 'Minced' | 'Sliced';
export type Weight = '500g' | '1kg' | '2kg' | '5kg';

export interface Product {
  id: string;
  name: string;
  category: Category;
  weight: Weight;
  price: number;
  rating: number;
  reviews: number;
  addedDaysAgo: number; // 0 = today
  preparation: Preparation;
  isNew: boolean;
  inStock: boolean;
  sameDayDelivery: boolean;
  newArrival: boolean;
  bestSeller: boolean;
  emoji: string;
  gradient: string; // tailwind gradient classes
}

export const CATEGORIES: Category[] = [
  'Chicken',
  'Beef',
  'Seafood',
  'Goat',
  'Pork',
  'Turkey',
  'BBQ',
  'Sausages',
  'Spices',
];

export const WEIGHTS: Weight[] = ['500g', '1kg', '2kg', '5kg'];
export const PREPARATIONS: Preparation[] = ['Whole', 'Cubed', 'Boneless', 'Minced', 'Sliced'];

export const PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: "Chef's Signature Spice Rub",
    category: 'Spices',
    weight: '500g',
    price: 2500,
    rating: 4.8,
    reviews: 45,
    addedDaysAgo: 0,
    preparation: 'Minced',
    isNew: true,
    inStock: true,
    sameDayDelivery: true,
    newArrival: true,
    bestSeller: false,
    emoji: '🌶️',
    gradient: 'from-amber-200 to-orange-300',
  },
  {
    id: 'p2',
    name: 'Premium Beef Sirloin Steak',
    category: 'Beef',
    weight: '1kg',
    price: 13500,
    rating: 4.9,
    reviews: 96,
    addedDaysAgo: 0,
    preparation: 'Sliced',
    isNew: true,
    inStock: true,
    sameDayDelivery: true,
    newArrival: false,
    bestSeller: true,
    emoji: '🥩',
    gradient: 'from-rose-200 to-red-300',
  },
  {
    id: 'p3',
    name: 'Whole Free-Range Chicken',
    category: 'Chicken',
    weight: '2kg',
    price: 8200,
    rating: 4.7,
    reviews: 112,
    addedDaysAgo: 1,
    preparation: 'Whole',
    isNew: false,
    inStock: true,
    sameDayDelivery: false,
    newArrival: false,
    bestSeller: true,
    emoji: '🍗',
    gradient: 'from-yellow-100 to-amber-200',
  },
  {
    id: 'p4',
    name: 'Atlantic Prawns',
    category: 'Seafood',
    weight: '500g',
    price: 9800,
    rating: 4.9,
    reviews: 88,
    addedDaysAgo: 0,
    preparation: 'Whole',
    isNew: true,
    inStock: true,
    sameDayDelivery: true,
    newArrival: true,
    bestSeller: false,
    emoji: '🦐',
    gradient: 'from-sky-100 to-cyan-200',
  },
  {
    id: 'p5',
    name: 'Goat Meat Cubes',
    category: 'Goat',
    weight: '1kg',
    price: 11000,
    rating: 4.6,
    reviews: 54,
    addedDaysAgo: 2,
    preparation: 'Cubed',
    isNew: false,
    inStock: true,
    sameDayDelivery: false,
    newArrival: false,
    bestSeller: false,
    emoji: '🐐',
    gradient: 'from-stone-200 to-orange-200',
  },
  {
    id: 'p6',
    name: 'Pork Chops',
    category: 'Pork',
    weight: '1kg',
    price: 10500,
    rating: 4.5,
    reviews: 37,
    addedDaysAgo: 3,
    preparation: 'Sliced',
    isNew: false,
    inStock: false,
    sameDayDelivery: false,
    newArrival: false,
    bestSeller: false,
    emoji: '🥓',
    gradient: 'from-pink-100 to-rose-200',
  },
  {
    id: 'p7',
    name: 'Turkey Breast Fillet',
    category: 'Turkey',
    weight: '1kg',
    price: 12800,
    rating: 4.8,
    reviews: 63,
    addedDaysAgo: 1,
    preparation: 'Boneless',
    isNew: false,
    inStock: true,
    sameDayDelivery: true,
    newArrival: false,
    bestSeller: false,
    emoji: '🦃',
    gradient: 'from-orange-100 to-amber-300',
  },
  {
    id: 'p8',
    name: 'Smoky BBQ Pork Ribs',
    category: 'BBQ',
    weight: '1kg',
    price: 14200,
    rating: 4.9,
    reviews: 120,
    addedDaysAgo: 0,
    preparation: 'Sliced',
    isNew: true,
    inStock: true,
    sameDayDelivery: true,
    newArrival: true,
    bestSeller: true,
    emoji: '🍖',
    gradient: 'from-red-200 to-orange-300',
  },
  {
    id: 'p9',
    name: 'Classic Beef Sausage Links',
    category: 'Sausages',
    weight: '500g',
    price: 6300,
    rating: 4.6,
    reviews: 41,
    addedDaysAgo: 4,
    preparation: 'Whole',
    isNew: false,
    inStock: true,
    sameDayDelivery: false,
    newArrival: false,
    bestSeller: false,
    emoji: '🌭',
    gradient: 'from-orange-200 to-red-200',
  },
  {
    id: 'p10',
    name: 'Premium Minced Beef',
    category: 'Beef',
    weight: '1kg',
    price: 9900,
    rating: 4.7,
    reviews: 72,
    addedDaysAgo: 2,
    preparation: 'Minced',
    isNew: false,
    inStock: true,
    sameDayDelivery: true,
    newArrival: false,
    bestSeller: false,
    emoji: '🥩',
    gradient: 'from-red-100 to-rose-300',
  },
  {
    id: 'p11',
    name: 'Suya Spice Mix',
    category: 'Spices',
    weight: '500g',
    price: 3200,
    rating: 4.8,
    reviews: 58,
    addedDaysAgo: 0,
    preparation: 'Minced',
    isNew: true,
    inStock: true,
    sameDayDelivery: true,
    newArrival: true,
    bestSeller: false,
    emoji: '🧂',
    gradient: 'from-amber-100 to-yellow-300',
  },
  {
    id: 'p12',
    name: 'Fresh Catfish',
    category: 'Seafood',
    weight: '1kg',
    price: 7500,
    rating: 4.5,
    reviews: 29,
    addedDaysAgo: 5,
    preparation: 'Whole',
    isNew: false,
    inStock: true,
    sameDayDelivery: false,
    newArrival: false,
    bestSeller: false,
    emoji: '🐟',
    gradient: 'from-cyan-100 to-sky-200',
  },
];

export function formatNaira(amount: number): string {
  return '₦' + amount.toLocaleString('en-NG');
}
